[project]
name = "repl-nix-exceldiffvisualizer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.3",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "streamlit-aggrid>=1.0.5",
    "streamlit>=1.40.2",
    "xlwings>=0.33.4",
]
